repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-import-order]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-python-dateutil, types-requests, types-PyYAML]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
    -   id: python-use-type-annotations

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        additional_dependencies: [mdformat-gfm, mdformat-black, mdformat-toc]
        args: [--wrap=80]
